app:
    resource: "@AppBundle/Controller/"
    type:     annotation

cls_admin:
    resource: "@AppBundle/Resources/config/routing/admin/routing.yml"
    prefix:   /admin

cls_user:
    resource: "@AppBundle/Resources/config/routing/user/all.yml"
    prefix:   /

cls_home:
    resource: "@AppBundle/Resources/config/routing/home_routing.yml"
    prefix:   /

cls_category:
    resource: "@AppBundle/Resources/config/routing/category_routing.yml"
    prefix:   /

cls_tag:
    resource: "@AppBundle/Resources/config/routing/tags_routing.yml"
    prefix:   /